name: Build and Publish Docker
on: [push]
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@master
   - name: Publish to Docker Repository
     uses: elgohr/Publish-Docker-Github-Action@master
     with:
       name: lim1942/filebrowser
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}
